name: linker
version: 1.0.0+1
publish_to: none
description: Linker is an App to save Your Links
environment:
  sdk: '>=2.16.0-134.5.beta <3.0.0'

dependencies:
  animated_text_kit: ^4.2.1
  auto_size_text: ^3.0.0
  clipboard: ^0.1.3
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_in_app_messaging: ^0.6.0+7
  firebase_messaging: ^11.2.6
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  fluttertoast: ^8.0.8
  get: ^4.6.1
  get_storage: ^2.0.3
  google_mobile_ads: ^1.1.0
  google_sign_in: ^5.2.3
  local_auth: ^1.1.10
  share_plus: ^3.0.4
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/MyFlutterApp.ttf
    - family: Search
      fonts:
        - asset: assets/Search.ttf
